### ISSUE TITLE
能直接在IBM上搭建Aria2服务端么？

### ISSUE THREAD

**Issue by meichuanyi** [artxia/IBM-tele-aria2#2]
这个上面的Aria2服务器是不是还要另外搭建？

**Comment by meichuanyi** [comment]
https://github.com/P3TERX/aria2.sh 
把这个直接安装就可以了，怎么设置actions呀？（ps：这个流量过大ibm会被封号么？）

**Comment by artxia** [comment]
Aria2的下载和上传都是由你自己搭建Aria2所在的平台运行，IBM只是运行bot传输命令，不会有大流量。

**Comment by meichuanyi** [comment]
对，我就是想把Aria2上传下载的平台一块搭在上面o(╥﹏╥)o

**Comment by artxia** [comment]
> 对，我就是想把Aria2上传下载的平台一块搭在上面o(╥﹏╥)o

IBM Cloud Fonudray 只是一个容器，免费版磁盘空间只有1G。
（当然，你有其他办法可自行尝试，本项目只是搭建Aria2管理bot）
