### ISSUE TITLE
可以出一个网页版的AriaNg吗？类似heroku的AriaNg

### ISSUE THREAD

**Issue by LimitBreaker01** [artxia/IBM-tele-aria2#3]
大佬：
该项目支持TG机器人，能支持下载上传到GD或者OD吗？怎么操作？
或者出一个类似heroku的ariang网页版的

**Comment by artxia** [comment]
本项目只是提供便利，方便大家 在ibm容器上搭建` tele-aria2` 机器人。
该机器人只是用来`控制已有aria2服务器的上传下载`，并不是搭建一个新的aria2服务器。

 tele-aria2机器人原项目是 https://github.com/HouCoder/tele-aria2


ps:
1、你想在web使用AriaNg，可以试试AriaNg的chrome插件。
2、想通过本项目搭建的机器人实现自动上传GD，需要你自行搭建的aria2服务器具备这个能力。推荐这个项目https://github.com/P3TERX/aria2.sh
