### ISSUE TITLE
多管理用户 

### ISSUE THREAD

**Issue by shzxm** [artxia/IBM-tele-aria2#5]
不知道是否支持多管理用户 就是`TELEGRAM_ID`那个地方可否`11111,11112` 这样两个管理员 同时使用 

所使用的aria2 bot项目是支持的 `https://github.com/HouCoder/tele-aria2`

不知道作者这个项目怎么填写id参数

还有，如果修改了配置参数 会自动重新部署，还是需要手动删除原有ibm主机 在重新自动部署

**Comment by artxia** [comment]
1、多管理员。原核心项目支持本项目就支持。格式为`123,456,789`
2、原核心项目能用的配置参数都在说明部分Key这里配置。仅剩`max-index`，可自行修改`auto_install.yml`文件下`config.json`部分。
3、修改了参数需要完全重新运行说明中的第四步，即可自动重新安装一次。不需要管ibm

**Comment by shzxm** [comment]
感谢作者~
