### ISSUE TITLE
建议添加核心项目隔时重启功能,核心项目的bug

### ISSUE THREAD

**Issue by shzxm** [artxia/IBM-tele-aria2#6]
建议添加核心项目[tele-aria2](https://github.com/HouCoder/tele-aria2)的定时或者隔时重启,
核心项目的bug导致使用几小时后,bot就会无反应状态.
已给原核心项目提issue,但是估计小bug修复的可能新较低,
所以找了一个简单的办法,隔时重启tele-aria2就可以了.

**Comment by artxia** [comment]
目前我没有遇到这种情况

IBM 能看到日志吗？贴出来看看？
因为本项目设置了IBM容器每周重启，可以看一下tg带日期的截图？看看 bot 的 ibm 容器在每周重启后，多长时间不能反应？

**Comment by shzxm** [comment]
遇到的状况表现为，部署完成后的一段时间核心项目是没有问题可以正常使用的，但是隔一段时间，核心就会陷入无反应状态，直至重启ibm过重新部署才可以
不知道你有没有遇到过
我之前部署在本地的时候，解决办法就是重启bot服务，就可以恢复正常了

**Comment by shzxm** [comment]
我去看看日志

**Comment by shzxm** [comment]
idm看不到日志,
![image](https://user-images.githubusercontent.com/9905297/110647454-cf9a5980-81f2-11eb-9ce9-3b91fae71306.png)
2021-03-10 22:39重启的.看看什么时候会死机

**Comment by artxia** [comment]
> 遇到的状况表现为，部署完成后的一段时间核心项目是没有问题可以正常使用的，但是隔一段时间，核心就会陷入无反应状态，直至重启ibm过重新部署才可以
> 不知道你有没有遇到过
> 我之前部署在本地的时候，解决办法就是重启bot服务，就可以恢复正常了

你后面这个截图也看不到具体日期
“一段时间”，具体是多久？如果是一两个月左右的话，应该是 IBM 关闭了容器。你只需开启项目中的每周重启就行。

IBM 容器本身有一些限制，在一段时间没有部署操作后会自动关闭挂起。这也是为什么我在项目中部署了每周自动重启IBM容器的脚本。
IBM 容器有点类似 docker 容器，需要有核心进程才能保持开启，也就是说重启核心进程相当于重启整个容器（貌似也能用脚本单独重启进程，不过再加就有点本末倒置了）。又因为 IBM 容器每次重启就会完全重置成最后一次部署状态，所以里面的记录等都会被清除。这就导致不建议太短时间内重启，因此我设定是每周重启一次。

**Comment by shzxm** [comment]
每周重启是在哪里开启的.我去开启试一下,

**Comment by artxia** [comment]
> 每周重启是在哪里开启的.我去开启试一下,

`auto_restart.yml` 文件，随便编辑一下；或者**Run workflow**手动运行
